"""Web scraper for live Premier League standings from OneFootball."""

import logging
import re
from typing import Optional

import requests
from bs4 import BeautifulSoup

from services.team_normalizer import normalize

logger = logging.getLogger(__name__)

STANDINGS_URL = "https://onefootball.com/en/competition/premier-league-9/table"

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/120.0.0.0 Safari/537.36"
    ),
    "Accept-Language": "en-US,en;q=0.9",
}


def _parse_int(value: str) -> Optional[int]:
    """Parse a stat cell that may be '+3', '-1', or plain digits."""
    try:
        return int(value.replace("+", "").strip())
    except (ValueError, AttributeError):
        return None


def scrape_standings() -> list[dict]:
    """
    Scrape the current Premier League standings from OneFootball.

    Returns a list of dicts with keys:
        position, team_short, played, won, drawn, lost,
        goals_for, goals_against, goal_difference, points

    Note: OneFootball's table does not expose Goals For / Goals Against
    as separate columns — only Goal Difference is available. goals_for
    and goals_against will be None unless derivable.

    Note: CSS class names on OneFootball are generated by CSS Modules and
    may change between site deploys. If scraping stops working, inspect
    the live HTML and update the class selectors below.
    """
    try:
        response = requests.get(STANDINGS_URL, headers=HEADERS, timeout=15)
        response.raise_for_status()
    except requests.RequestException as exc:
        logger.error("Failed to fetch OneFootball standings: %s", exc)
        return []

    page = BeautifulSoup(response.text, "lxml")

    # Row selector — CSS Module class names that may change over time
    rows = page.find_all("li", class_=re.compile(r"Standing_standings__row"))

    if not rows:
        # Fallback: try any <li> inside a standings list
        rows = page.find_all("li", class_=re.compile(r"standings.*row", re.I))

    if not rows:
        logger.warning(
            "No standings rows found on OneFootball. "
            "The page structure may have changed — check CSS selectors."
        )
        return []

    results = []
    for row in rows:
        # Cell selector
        cells = row.find_all("div", class_=re.compile(r"Standing_standings__cell"))

        # Team name
        team_elem = row.find("p", class_=re.compile(r"Standing_standings__teamName"))
        if not team_elem:
            team_elem = row.find("p", class_=re.compile(r"teamName", re.I))

        if not team_elem or len(cells) < 8:
            continue

        raw_team = team_elem.text.strip()
        team_short = normalize(raw_team)

        try:
            position = _parse_int(cells[0].text.strip())
            played = _parse_int(cells[2].text.strip())
            won = _parse_int(cells[3].text.strip())
            drawn = _parse_int(cells[4].text.strip())
            lost = _parse_int(cells[5].text.strip())
            goal_difference = _parse_int(cells[6].text.strip())
            points = _parse_int(cells[7].text.strip())
        except IndexError:
            logger.warning("Unexpected row structure for team '%s' — skipping.", raw_team)
            continue

        # Derive goals_for / goals_against if possible (not directly available)
        # They remain None — the frontend/DB can handle null
        results.append({
            "position": position,
            "team_short": team_short,
            "played": played,
            "won": won,
            "drawn": drawn,
            "lost": lost,
            "goals_for": None,
            "goals_against": None,
            "goal_difference": goal_difference,
            "points": points,
        })

    logger.info("Scraped %d teams from OneFootball standings.", len(results))
    return results
